package org.proptit.localchat.common.enums;

public enum TypeDataPacket {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    CHAT_MESSAGE,
    GET_ALL_USERS,
    RETURN_ALL_USERS,
    GET_ONLINE_USERS,
    RETURN_ONLINE_USERS,
    DELETE_USER_REQUEST,
    ADD_USER_REQUEST,
    ADD_ACCOUNT_FAILURE,
    ADD_ACCOUNT_SUCCESS,
    CALL_SIGNAL

}
