package org.proptit.localchat.common.enums;

public enum TypeDataPacket {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    CHAT_MESSAGE,
    GET_ALL_USERS,
    RETURN_ALL_USERS,
    GET_ONLINE_USERS,
    RETURN_ONLINE_USERS,
    DELETE_USER_REQUEST,
    ADD_USER_REQUEST,
    ADD_ACCOUNT_FAILURE,
    ADD_ACCOUNT_SUCCESS,

    GET_HISTORY_REQUEST,
    RETURN_HISTORY,
    GET_CHAT_CONTACTS,
    RETURN_CHAT_CONTACTS,


    DOWNLOAD_FILE_RESPONSE,
    DOWNLOAD_IMAGE_RESPONSE,
    DOWNLOAD_IMAGE_REQUEST,
    DOWNLOAD_FILE_REQUEST,



    CALL_SIGNAL,
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_SUCCESS,
    UPDATE_PROFILE_FAILURE,


    UPDATE_PASS_REQUEST,
    UPDATE_PASS_SUCCESS,
    UPDATE_PASS_FAILURE,
    RETURN_OFFLINE_NOTIFICATIONS,
    GET_OFFLINE_NOTIFICATIONS,
    MARK_AS_READ,


    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAILURE,

    GET_GROUP_HISTORY_REQUEST,

    GET_MY_GROUPS_REQUEST,
    RETURN_MY_GROUPS,
}
